# Generated by Django 3.2.25 on 2024-05-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='forks_count',
            new_name='forks',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='stargazers_count',
            new_name='stars',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='html_url',
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
